package com.example.ui.theme

import androidx.annotation.StringRes
import androidx.compose.ui.graphics.Color
import com.example.R

enum class DarkModePreference {
  SYSTEM,
  DARK,
  LIGHT
}

enum class ColorTheme(
  @StringRes val titleRes: Int,
  val previewPrimary: Color,
  val previewBackground: Color,
  // Light Palette
  val primaryLight: Color,
  val onPrimaryLight: Color,
  val primaryContainerLight: Color,
  val onPrimaryContainerLight: Color,
  val secondaryLight: Color,
  val secondaryContainerLight: Color,
  val onSecondaryContainerLight: Color,
  val surfaceLight: Color,
  val onSurfaceLight: Color,
  val surfaceVariantLight: Color,
  val onSurfaceVariantLight: Color,
  // Dark Palette
  val primaryDark: Color,
  val onPrimaryDark: Color,
  val primaryContainerDark: Color,
  val onPrimaryContainerDark: Color,
  val secondaryDark: Color,
  val secondaryContainerDark: Color,
  val onSecondaryContainerDark: Color,
  val surfaceDark: Color,
  val onSurfaceDark: Color,
  val surfaceVariantDark: Color,
  val onSurfaceVariantDark: Color
) {
  SUNSET_AMBER(
    titleRes = R.string.theme_sunset_amber,
    previewPrimary = Color(0xFFF97316),
    previewBackground = Color(0xFF0F172A),
    primaryLight = Color(0xFFEA580C),
    onPrimaryLight = Color(0xFFFFFFFF),
    primaryContainerLight = Color(0xFFFFEDD5),
    onPrimaryContainerLight = Color(0xFF7C2D12),
    secondaryLight = Color(0xFF475569),
    secondaryContainerLight = Color(0xFFE2E8F0),
    onSecondaryContainerLight = Color(0xFF1E293B),
    surfaceLight = Color(0xFFF8FAFC),
    onSurfaceLight = Color(0xFF0F172A),
    surfaceVariantLight = Color(0xFFE2E8F0),
    onSurfaceVariantLight = Color(0xFF334155),
    primaryDark = Color(0xFFFB923C),
    onPrimaryDark = Color(0xFF431407),
    primaryContainerDark = Color(0xFF7C2D12),
    onPrimaryContainerDark = Color(0xFFFFEDD5),
    secondaryDark = Color(0xFF334155),
    secondaryContainerDark = Color(0xFF1E293B),
    onSecondaryContainerDark = Color(0xFFE2E8F0),
    surfaceDark = Color(0xFF0F172A),
    onSurfaceDark = Color(0xFFF8FAFC),
    surfaceVariantDark = Color(0xFF1E293B),
    onSurfaceVariantDark = Color(0xFFCBD5E1)
  ),

  CYBER_PURPLE(
    titleRes = R.string.theme_cyber_purple,
    previewPrimary = Color(0xFFA855F7),
    previewBackground = Color(0xFF13091B),
    primaryLight = Color(0xFF9333EA),
    onPrimaryLight = Color(0xFFFFFFFF),
    primaryContainerLight = Color(0xFFF3E8FF),
    onPrimaryContainerLight = Color(0xFF581C87),
    secondaryLight = Color(0xFF6B7280),
    secondaryContainerLight = Color(0xFFE5E7EB),
    onSecondaryContainerLight = Color(0xFF1F2937),
    surfaceLight = Color(0xFFFAF5FF),
    onSurfaceLight = Color(0xFF1E1035),
    surfaceVariantLight = Color(0xFFE9D5FF),
    onSurfaceVariantLight = Color(0xFF4C1D95),
    primaryDark = Color(0xFFC084FC),
    onPrimaryDark = Color(0xFF3B0764),
    primaryContainerDark = Color(0xFF581C87),
    onPrimaryContainerDark = Color(0xFFF3E8FF),
    secondaryDark = Color(0xFF374151),
    secondaryContainerDark = Color(0xFF1F2937),
    onSecondaryContainerDark = Color(0xFFE5E7EB),
    surfaceDark = Color(0xFF13091B),
    onSurfaceDark = Color(0xFFF3E8FF),
    surfaceVariantDark = Color(0xFF261238),
    onSurfaceVariantDark = Color(0xFFE9D5FF)
  ),

  EMERALD_MINT(
    titleRes = R.string.theme_emerald_mint,
    previewPrimary = Color(0xFF10B981),
    previewBackground = Color(0xFF061A14),
    primaryLight = Color(0xFF059669),
    onPrimaryLight = Color(0xFFFFFFFF),
    primaryContainerLight = Color(0xFFD1FAE5),
    onPrimaryContainerLight = Color(0xFF064E3B),
    secondaryLight = Color(0xFF4B5563),
    secondaryContainerLight = Color(0xFFE5E7EB),
    onSecondaryContainerLight = Color(0xFF1F2937),
    surfaceLight = Color(0xFFF0FDF4),
    onSurfaceLight = Color(0xFF06281D),
    surfaceVariantLight = Color(0xFFA7F3D0),
    onSurfaceVariantLight = Color(0xFF065F46),
    primaryDark = Color(0xFF34D399),
    onPrimaryDark = Color(0xFF022C22),
    primaryContainerDark = Color(0xFF064E3B),
    onPrimaryContainerDark = Color(0xFFD1FAE5),
    secondaryDark = Color(0xFF374151),
    secondaryContainerDark = Color(0xFF1F2937),
    onSecondaryContainerDark = Color(0xFFE5E7EB),
    surfaceDark = Color(0xFF061A14),
    onSurfaceDark = Color(0xFFECFDF5),
    surfaceVariantDark = Color(0xFF0D3327),
    onSurfaceVariantDark = Color(0xFFA7F3D0)
  ),

  OCEAN_BLUE(
    titleRes = R.string.theme_ocean_blue,
    previewPrimary = Color(0xFF0284C7),
    previewBackground = Color(0xFF081426),
    primaryLight = Color(0xFF0284C7),
    onPrimaryLight = Color(0xFFFFFFFF),
    primaryContainerLight = Color(0xFFE0F2FE),
    onPrimaryContainerLight = Color(0xFF075985),
    secondaryLight = Color(0xFF475569),
    secondaryContainerLight = Color(0xFFE2E8F0),
    onSecondaryContainerLight = Color(0xFF1E293B),
    surfaceLight = Color(0xFFF0F9FF),
    onSurfaceLight = Color(0xFF082F49),
    surfaceVariantLight = Color(0xFFBAE6FD),
    onSurfaceVariantLight = Color(0xFF0369A1),
    primaryDark = Color(0xFF38BDF8),
    onPrimaryDark = Color(0xFF082F49),
    primaryContainerDark = Color(0xFF075985),
    onPrimaryContainerDark = Color(0xFFE0F2FE),
    secondaryDark = Color(0xFF334155),
    secondaryContainerDark = Color(0xFF1E293B),
    onSecondaryContainerDark = Color(0xFFE2E8F0),
    surfaceDark = Color(0xFF081426),
    onSurfaceDark = Color(0xFFF0F9FF),
    surfaceVariantDark = Color(0xFF0E223D),
    onSurfaceVariantDark = Color(0xFFBAE6FD)
  ),

  CRIMSON_ROSE(
    titleRes = R.string.theme_crimson_rose,
    previewPrimary = Color(0xFFF43F5E),
    previewBackground = Color(0xFF1C0A11),
    primaryLight = Color(0xFFE11D48),
    onPrimaryLight = Color(0xFFFFFFFF),
    primaryContainerLight = Color(0xFFFFE4E6),
    onPrimaryContainerLight = Color(0xFF881337),
    secondaryLight = Color(0xFF64748B),
    secondaryContainerLight = Color(0xFFF1F5F9),
    onSecondaryContainerLight = Color(0xFF0F172A),
    surfaceLight = Color(0xFFFFF1F2),
    onSurfaceLight = Color(0xFF4C0519),
    surfaceVariantLight = Color(0xFFFECDD3),
    onSurfaceVariantLight = Color(0xFF9F1239),
    primaryDark = Color(0xFFFB7185),
    onPrimaryDark = Color(0xFF4C0519),
    primaryContainerDark = Color(0xFF881337),
    onPrimaryContainerDark = Color(0xFFFFE4E6),
    secondaryDark = Color(0xFF334155),
    secondaryContainerDark = Color(0xFF1E293B),
    onSecondaryContainerDark = Color(0xFFF1F5F9),
    surfaceDark = Color(0xFF1C0A11),
    onSurfaceDark = Color(0xFFFFF1F2),
    surfaceVariantDark = Color(0xFF321320),
    onSurfaceVariantDark = Color(0xFFFECDD3)
  ),

  CLASSIC_SLATE(
    titleRes = R.string.theme_classic_slate,
    previewPrimary = Color(0xFF64748B),
    previewBackground = Color(0xFF18181B),
    primaryLight = Color(0xFF475569),
    onPrimaryLight = Color(0xFFFFFFFF),
    primaryContainerLight = Color(0xFFF1F5F9),
    onPrimaryContainerLight = Color(0xFF0F172A),
    secondaryLight = Color(0xFF64748B),
    secondaryContainerLight = Color(0xFFE2E8F0),
    onSecondaryContainerLight = Color(0xFF1E293B),
    surfaceLight = Color(0xFFFAFAFA),
    onSurfaceLight = Color(0xFF18181B),
    surfaceVariantLight = Color(0xFFE4E4E7),
    onSurfaceVariantLight = Color(0xFF27272A),
    primaryDark = Color(0xFF94A3B8),
    onPrimaryDark = Color(0xFF0F172A),
    primaryContainerDark = Color(0xFF334155),
    onPrimaryContainerDark = Color(0xFFF8FAFC),
    secondaryDark = Color(0xFF52525B),
    secondaryContainerDark = Color(0xFF27272A),
    onSecondaryContainerDark = Color(0xFFE4E4E7),
    surfaceDark = Color(0xFF18181B),
    onSurfaceDark = Color(0xFFF4F4F5),
    surfaceVariantDark = Color(0xFF27272A),
    onSurfaceVariantDark = Color(0xFFD4D4D8)
  )
}
